[+]Server Connection with Frontend
MostlyKIGuess/handwritten-to-LaTeX-demo pull request #16
Opened 2024-07-13 10:32 UTC by MostlyKIGuess

# Backend

## Contour_filtering.py
- Biggest issue in this world is this file, model works fine, we need to figure out how to add margins to the images and separate them out better.
- No need for threshold here so removed it.

### resnet18_vgg16.py
- Added more models for further training purposes.

### Server.py
- was mostly done by @0x0is1 . And is left as it is.

# Frontend

### canvas.js
- Removed unnecessary overlay canvas. Set line default to 2 for better results.

### App.js
- checkPrediction function added which will loop over the request after the image is uploaded by the user.

2024-07-13 13:28 UTC, 0x0is1 approved these changes

2024-07-13 13:28 UTC, 0x0is1 commented on Backend/request_handler/server.py
> +    return prediction_text
Looks good.

2024-07-13 14:25 UTC, 0x0is1 commented
@MostlyKIGuess can i expect change in latex db thing and review notes by today?

2024-07-14 04:33 UTC, MostlyKIGuess commented
> @MostlyKIGuess can i expect change in latex db thing and review notes by today?

Done, Check the contour filter once!

2024-07-14 08:20 UTC, 0x0is1 commented
@MostlyKIGuess changes requires testing.

2024-07-14 08:30 UTC, 0x0is1 requested changes

2024-07-14 08:30 UTC, 0x0is1 commented on Backend/trainmodel.py
> +            cv2.imwrite(image_path, bw_image)
Physical dataset writing wasnt required and is considered a bad practice.

2024-07-14 08:30 UTC, 0x0is1 commented on Backend/trainmodel.py
> +
Yeah a bunch of whitespaces helps.

2024-07-14 08:33 UTC, 0x0is1 requested changes

2024-07-14 08:33 UTC, 0x0is1 commented on Backend/learner/resnet18_vgg16.py
> +            image = Image.fromarray(bw_image).convert('RGB')  # Convert to PIL Image and RGB mode
Replaced dataset tuning without touching datasets.

2024-07-14 08:33 UTC, 0x0is1 commented on Backend/trainmodel.py
> +
This wasnt required as this is already done in trainer module.

2024-07-14 09:09 UTC, 0x0is1 commented
Fuck i reverted wrong commit

2024-07-14 09:17 UTC, MostlyKIGuess commented
bro you literally removed the best commit 😭

2024-07-15 00:40 UTC, MostlyKIGuess commented
Make the Electron PR today @0x0is1 ?

2024-07-15 05:00 UTC, 0x0is1 approved these changes

2024-07-15 05:00 UTC, 0x0is1 commented on Backend/trainmodel.py
> -    prediction = classifier.predict(image_path=pil_image)
Thanks for fixing the fuckups.

2024-07-15 05:00 UTC, 0x0is1 commented
> Make the Electron PR today @0x0is1 ?

Yes, Sure.

2024-07-15 05:01 UTC, merged